### PR TITLE
[wait_action] Fix for review bug

### PR DESCRIPTION
**Pull request by nilsbore**
@hawesie and @BFALacerda will have to decide if this is to be merged. It is a fix for a bug we had during the review where the robot failed to call the wait_action when waiting or charging.

### CODE REVIEW

**Comment by hawesie** [comment]
This will stop the "wake me up" dialogue on the robot from working, as it monitors the presence and absence of that service. I wonder why the `end_wait_srv.shutdown()` was not removing the service?

**Comment by cdondrup** [comment]
We haven't updated Linda in a while and she does not show the same behaviour as Rosie. We are still commit d578d33115c69c1394e42b17e0a76330d4fa8db0
Did something break it afterwards?

**Comment by bfalacerda** [comment]
Maybe the problem is https://github.com/strands-project/strands_utils/blob/hydro-devel/wait_action/scripts/wait_node.py#L21. Once you set the server to a terminal state it can run another execute callback in another thread, even though the current one has not  terminated yet. Then the new cb tries to register the service before the current one unregisters it. Or maybe I don't have a clue of what's going on :)

**Comment by nilsbore** [comment]
@hawesie @BFALacerda Can we close this then?

**Comment by bfalacerda** [comment]
@hawesie I remember you saying that this solution wasn't good because there is another node that checks if the service is running, and with this approach we always have the service running. Not sure of this though, it was a long time ago

**Comment by hawesie** [comment]
Yes, for that reason it's not a good solution.

**Pull request closed without merging**
