### PR TITLE
strands_datacentre

### PR DESCRIPTION
**Pull request by cburbridge**
This new  package contains a single node that starts a MongoDB server, which can be used to store anything. I imagine using it to store both configuration data (eg. maps with meta-data ( patrolling waypoints), charging station parameters, diagnostics "on-call" contacts) and general long-term experiences (ros messages, particularly QSR rerpresentations of perception).

This package requires MongoDB and python-pmongo:

```
sudo apt-get install mongodb
sudo apt-get install python-pymongo
```

C++ and Python mongo wrappers are available, so I imagine client programs will often communicate directly with MongoDB directly rather than through ros service calls. However, for system parameters I suggest we create another node that loads parameters from the mongodb onto the ros parameter server, overlayed on top of a set of standard parameters allowing each partner to have there own config.

### CODE REVIEW

**Comment by cburbridge** [comment]
Yes, I agree, mongodb_log looks useful for logging ros topics in a way that allows us to execute queries later, and I expect that I will use it at least in part.

My other intended uses for the database in the short-term:
- to store configuration data, particularly site-specific data such as charging station calibration parameters
- to store maps and meta-data, specifically I will integrate with the autonomous_patrolling to keep the patrol points attached to maps. 

This package (strands_datacentre) provides a rosified method of starting mongod. It is similar to the wrapper in mongo_ros / warehouse_ros / warehouse_wg, but (hopefully) closes the database properly on exit and avoids a dependency on warehouse_ros just for the wrapper. Once started, the logging nodes in mongodb_log will be able to use this database server.

The package also provides a node that manages configuration data. Two levels of configuration are stored in the "config" database:
- default parameters are stored in the "defaults" collection; these are read from yaml files in the defaults/ folder in the package at start up, and are global across all sites and to be kep on github.
- local parameters are stored in the "local" collection; these override any same-named parameter in the "defaults" collection.
  All parameters are entered onto the ros parameter server at startup, and two services are provided for setting and getting local parameters (of course a direct connection to mongo would be possible too).

**Comment by marc-hanheide** [comment]
OK, that makes perfect sense to me and I was about to suggest something similar. Did I miss a discussion about this or did you just decide this is the right way to do it? Just wondering really, because it was on my list of things to bring up, but now I was surprised that somebody is working on it already (you're always two steps ahead of me). Anyway, I'll merge it because I think this is exactly what we need. However, we then need to educate people to use it for their configs. Have you talked to @gestom about it already? I assume so.

**Comment by marc-hanheide** [comment]
It needs some more documentation in README.md, though, but feel free to add that later.

**Comment by hawesie** [comment]
It would certainly be good to discuss these things on the strands-wp8 mailing list so we're working together and not risking duplicating effort.

**Pull request merged**
